apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    kube-job-cleaner/ttlSecondsAfterFinished: "30"
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never